export enum TypeOfProperty {
    RESIDENCIAL = "RESIDENCIAL",
    DUPLEX = "DUPLEX",
    DEPARTAMENTO = "DEPARTAMENTO",
    HABITACION = "HABITACION",
    OFICINA = "OFICINA",
    LOCAL_COMERCIAL = "LOCAL_COMERCIAL",
}