export enum ServiceType {
  RENT = "ALQUILER",
  DEPOSIT = "DEPOSITO",
  EXPENSES = "EXPENSAS",
  ELECTRICITY = "LUZ",
  WATER = "AGUA",
  GAS = "GAS",
  MUNICIPALITY = "MUNICIPALIDAD",
  NOT_APPLICABLE = "NO_APLICA"
}

export enum PaymentStatus {
  PAID = "PAGADO",
  PENDING = "PENDIENTE",
  EXPIRED = "VENCIDO"
}