name: Build and Deploy Backend

on:
  pull_request:
    types: [closed]
    branches: [dev-backend]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/footalent-backend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/footalent-backend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/footalent-backend:buildcache,mode=max

  deploy:
    if: github.event.pull_request.merged == true
    needs: build
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3

      - name: Install Koyeb CLI
        run: |
          curl -sSL https://koyeb.com/install.sh | sh
          echo "${HOME}/.koyeb/bin" >> $GITHUB_PATH

      - name: Redeploy service on Koyeb
        run: koyeb service redeploy rentarry/footalent-backend --token ${{ secrets.KOYEB_API_TOKEN }}